// <auto-generated />
namespace TaskList.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class PermissionForManipulationWithEmployeesIsAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PermissionForManipulationWithEmployeesIsAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "201712101437257_PermissionForManipulationWithEmployeesIsAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
